### ISSUE TITLE
Get xml text out unprocessed

### ISSUE THREAD

**Issue by MARTIMM** [supernovus/exemel#16]
When I do something like ```$xml-text ~= $xml-document.root;``` all text from XML::Text elements are processed in such a way that all whithespace is reduced to one space. For some elements like \<pre\>\</pre\> in html this is not desired. How can I change this? Or is another method needed in your package

**Comment by MARTIMM** [comment]
I've found a way to cope with it;
```
class My-xml::Text is XML::Text {
  method Str {
    return $.text;
  }
}
```
Then later instead of ``` $some-element.append(XML::Text.new(:$text)); ``` use the new class
``` $some-element.append(My-xml::Text.new(:$text)); ```

**Comment by supernovus** [comment]
I believe there are supposed to be ways of accessing the text in different ways, but it's been a while since I looked at the code. This should be made much more clear in the documentation, and probably simplified.

Thank you for bringing this to my attention.

**Comment by MARTIMM** [comment]
I am content with the method I found but yes, maybe some extra documentation. It's difficult to have examples for every possible situation though. There is one small thing left in the Str method of XML::Text. There is a ```:$strip``` parameter to that method which can not be used from the root of the document when serializing, so stripping leading and trailing spacing must be done in the users code before creating the text object.
