### ISSUE TITLE
XML prolog is not parsed correctly (patch not able to be attached)

### ISSUE THREAD

**Issue by pwd3** [supernovus/exemel#27]
If a XML input (file or string) has a XML prolog (<?xml.....) the version and encoding will have the quotes in them and on output will not parse correctly.

In addition the code looked like it would not handle a prolog with single quotes.

and 
the standalone parameter is not supported (at least it does not look like it is.

I fixed the first two items BUT while I have 26 years of Perl coding I am just starting on Perl 6.
Attached is (At lease I am going to try and attach) a git patch file with two commits that:

1) add a test (t/prolog.t) that tests out these issues and will fail on current master branch.
2) fixes the Grammar file to handle the single quote.
3) fixes XML.pm6 to remove the quotes from the version and encoding.

OK can't attach a patch file I will try and find a email address and send it to you.

**Comment by supernovus** [comment]
Noting that I merged your pull request which fixes most of this. I'm not sure about the standalone parameter, I haven't been very active with Perl 6 stuff for a while, so many of these libraries are in need of some polish.

**Comment by pwd3** [comment]
Thanks I am on vacation today and Monday but will test the production build

on Tuesday.


I am adding a set of examples (mostly as a tool to learn the XML package and may

improve the test and maybe add a tidy print function)


--
This email, and any files transmitted with it, are confidential
and intended solely for the use of the individual or entity to
whom they are addressed.  If you have received this email in error,
please advise postmaster@mdtsoft.com <mailto:postmaster@mdtsoft.com>.

3480 Preston Ridge Road
Suite 450
Alpharetta, GA 30005

Philip W. Dalrymple III <pwd@mdtsoft.com>
MDT Software - Automation Management Company
+1 678 297 1001<callto:+1%20678%20297%201001>
Fax +1 678 297 1003<callto:+1%20678%20297%201003>


________________________________
