### ISSUE TITLE
Error if tagname ~~ / '-' \d /

### ISSUE THREAD

**Issue by frithnanth** [supernovus/exemel#34]
This program:

use XML;
my $xml = from-xml-file('test.xml');

outputs an error when test.xml is like this (which passes the validation test here: http://www.w3schools.com/xml/xml_validator.asp):

&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
&lt;test&gt;
  &lt;greeting en=&quot;hello&quot;&gt;world&lt;/greeting&gt;
  &lt;for&gt;
    &lt;item-1&gt;Yes&lt;/item-1&gt;
    &lt;item-1&gt;No&lt;/item-1&gt;
    &lt;item-1&gt;Maybe&lt;/item-1&gt;
    &lt;item-1&gt;Who cares?&lt;/item-1&gt;
  &lt;/for&gt;
&lt;/test&gt;

but works fine if test.xml is:

&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
&lt;test&gt;
  &lt;greeting en=&quot;hello&quot;&gt;world&lt;/greeting&gt;
  &lt;for&gt;
    &lt;item-dash&gt;Yes&lt;/item-dash&gt;
    &lt;item-dash&gt;No&lt;/item-dash&gt;
    &lt;item-dash&gt;Maybe&lt;/item-dash&gt;
    &lt;item-dash&gt;Who cares?&lt;/item-dash&gt;
  &lt;/for&gt;
&lt;/test&gt;

**Comment by supernovus** [comment]
Interesting, that would indicate a problem with the XML::Grammer, it's been a while since I tinkered with grammars, but I will take a look when I have a chance and see what I can do to optimize it. Thank you for the report.

**Comment by fjwhittle** [comment]
Added a test for this to PR #39 which covers this functionality.

**Comment by supernovus** [comment]
I have merged PR #39 which should resolve this now. Thanks for the fix!

**Comment by fil512** [comment]
Cool!  I had a kludgey workaround to deal with this bug!
