### ISSUE TITLE
Break XML::Document (and others) into separate files

### ISSUE THREAD

**Issue by tony-o** [supernovus/exemel#35]
Would you oppose breaking the classes/roles into separate files so they can be exported from the module separately?  I'm asking because I'd like to use only `XML::Document` and the other `::Node` objects in the `NativeCall`(Expat) version of this module that I'm currently working on

**Comment by supernovus** [comment]
That sounds fine to me. I was planning on a libxml2 implementation to go along with the pure Perl 6 one when I was still actively working on these libraries. I'm glad to hear someone is making an Expat implementation.
