### ISSUE TITLE
translation of single quotes in attribute values is undesired

### ISSUE THREAD

**Issue by MARTIMM** [supernovus/exemel#51]
Hi,
The translation of a single quote in an attribute value to `&#39;` is not helping in some situations. An example is: `<img onclick="alert('clicked')" />`. In these cases the JavaScript is rendered unusable if it is translated into `<img onclick="alert(&#39;clicked&#39;)" />`.

Regards,
Marcel

**Comment by supernovus** [comment]
I think I'm going to look at rewriting how the Attributes are handled, which will hopefully resolve this long outstanding issue.
