### ISSUE TITLE
I don't think entities are being considered at all

### ISSUE THREAD

**Issue by Altreus** [supernovus/exemel#58]
I have an XML file with `&amp;` in it, and this is not decoded when I stringify the text node. The documentation doesn't mention XML entities at all, so I'm not sure whether to expect this or not.

```
<NAME>MARKS&amp;SPENCER</NAME>

say $doc.lookfor(:TAG('NAME') :SINGLE)[0]; # MARKS&amp;SPENCER
```

Although, one would at least expect a facility to decode it, which is also not provided.

Ideally, the user should never see an XML entity, and they would be encoded/decoded transparently along the way.

**Comment by supernovus** [comment]
There is currently no XML entity support in the base library. It's one of the things I've been planning on doing for several years. When I do implement it, I'll have a core parsing library, built in support for the 5 predefined XML entities, plus at least a limited HTML set as a separate plugin.

**Comment by supernovus** [comment]
Actually, looking closer, someone added extremely minimal entity handling to Attribute values, but not to Text nodes. I'm making a more generic class that will simply offer a function called decode-entities() which will be used by the XML::Text.string() method to return a friendlier string.

**Comment by supernovus** [comment]
I referenced the wrong issue on the commit which adds XML::Entity.

See ./t/entities.t and ./t/entities.xml for an example.
See ./lib/XML/Entity.pm6 for the method which decodes entities. It supports the 5 predefined XML entities, plus decimal and hexidecimal numeric entities.

**Comment by supernovus** [comment]
See the new t/custom-entities.t for an example of custom entity support.
I'm also going to make a new library called XML::Entity::HTML which will be a full set of all recognized HTML 5 entities for use with XHTML 5 documents. This will be it's own package in it's own repository.

**Comment by supernovus** [comment]
See https://github.com/supernovus/xml-entity-html for the XHTML 5 entity support.

**Comment by supernovus** [comment]
With the features added in the last couple of days, I'm calling this done.
